# main text of home
name: Steven Simoni
bio: A guy who wants to be witty

# twitter summary info
description: Hi my name is Steven

picture: assets/images/picture.jpg

url: http://kr4ng.github.io
# url: http://koppl.in/violet
# your url: http://USERNAME.github.io

# if you don't have any of social below, comment the line
facebook: steven.m.simoni
twitter: StevenSimoni
github: kr4ng
email: steve@stevensimoni.com

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]